language: cpp

compiler:
  - gcc

env:
  - LIBUV_VERSION=1.0.2

before_script:
  # install libuv
  - curl -L http://dist.libuv.org/dist/v${LIBUV_VERSION}/libuv-v${LIBUV_VERSION}.tar.gz | tar xzf -
  - (cd libuv-${LIBUV_VERSION} && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install)
  # generate makefile
  - cmake .

script:
  - make

os:
  - linux
